### ISSUE TITLE
Minecraft Crashes once launcher window disappears 

### ISSUE THREAD

**Issue by leifadev** [IzzelAliz/MixinLoader#1]
Once the green bar finished and Minecraft started to launch, it crashed.

I couldn't get the full log but here is the most I could get:
https://pastebin.com/CUphLebZ
I used both of your versions and they both didn't work (most likely same error)

Using this with OptiForge
I would really love to see this work!

Thanks!

**Comment by IzzelAliz** [comment]
It is very likely that OptiForge has problems with its code, something like a mixin injection failure.
MixinLoader worked as intended.

**Comment by leifadev** [comment]
Ok, thanks! Is there any way I can contact you? Is there any time you will improve the code?
